onlyBuiltDependencies:
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - esbuild
  - msgpackr-extract

packageManagerStrictVersion: true

publicHoistPattern:
  - '*eslint*'
  - '*@nextui-org/*'
  - '@uploadthing/*'
  - '@t3-oss/*'
  - '@sentry/core'
  - import-in-the-middle
  - require-in-the-middle

savePrefix: ''
