onlyBuiltDependencies:
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - msgpackr-extract
packageManagerStrictVersion: true
publicHoistPattern:
  - '*eslint*'
  - '*@nextui-org/*'
  - '@uploadthing/*'
  - '@t3-oss/*'
  - '@sentry/core'
savePrefix: ''
